### ISSUE TITLE
Java License not working on RedHat installation

### ISSUE THREAD

**Issue by rcmoutinho** [ansiblebit/oracle-java#108]
I'm using this role to install Nexus 3 ([nexus-oss](https://github.com/ansible-ThoTeam/nexus3-oss#dependencies)). Since always it was working fine but now it isn't accepting java license anymore.

Here is the error: (a timeout due to this license problem)

![screen shot 2019-01-22 at 07 21 27](https://user-images.githubusercontent.com/11356237/51524971-6a1e5f80-1e16-11e9-82c9-069341d36072.png)

I'm using the same suggestion to RedHat distros as this project documentation says.

```
oracle_java_use_defaults: no
oracle_java_dir_source: '/usr/local/src'
oracle_java_download_timeout: 60  
oracle_java_rpm_filename: 'jdk-8u191-linux-x64.rpm'
oracle_java_home: '/usr/java/default'
oracle_java_os_supported: yes
oracle_java_rpm_url: 'http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.rpm'
oracle_java_rpm_validate_certs: yes
oracle_java_set_as_default: no
oracle_java_version_string: 1.8.0_191
```

Any clues?

This is the file from where the Java download request is done:
https://github.com/ansiblebit/oracle-java/blob/master/tasks/installation/redhat/main.yml#L8

Thanks for your help 🙂

**Comment by steenzout** [comment]
I would guess that the given rpm file is not available anymore.

I saw a fork yesterday by someone who updated the download URLs but didn't send a PR. :)

I'll try and get to this tonight.

**Comment by d4rkd0s** [comment]
@steenzout  any updates?

I'm in the same boat. We are pondering just offloading the RPM to a local machine to us. 

Oracle is the worst.

**Comment by d4rkd0s** [comment]
@rcmoutinho I noticed you are downloading Java 1.8 (Java 8 as it's called)
I did some research and no only are the URLs to download different. But its EOL from Oracle.
![image](https://user-images.githubusercontent.com/2348814/52432139-ee373f00-2ac6-11e9-8a80-3c54cecdd0f7.png)

Probably best using something higher than Java 8 if you want to not run into more issues. Of course this for us means a new project to convert our applications to support higher than Java 8.

**Comment by rcmoutinho** [comment]
@d4rkd0s for sure a version update would fix it but I'm using this role to install Nexus 3 ([nexus-oss](https://github.com/ansible-ThoTeam/nexus3-oss#dependencies)).

So, maybe we can try to switch for using OpenJDK or I can open an issue on the Nexus 3 role project so we can find a different way to install.

**Comment by d4rkd0s** [comment]
@rcmoutinho I feel your pain, we are also considering OpenJDK

**Comment by rcmoutinho** [comment]
For the ones that need to install Java 8 and Nexus 3, [this comment](https://github.com/ansible-ThoTeam/nexus3-oss/issues/140#issuecomment-462027234) solves the issue. Moving to OpenJDK in favor to complete [nexus-oss](https://github.com/ansible-ThoTeam/nexus3-oss#dependencies) ansible role.

**Comment by steenzout** [comment]
try this:

```
- hosts: servers
  roles:
      - role: ansiblebit.oracle-java
        oracle_java_use_defaults: no
        oracle_java_dir_source: '/usr/local/src'
        oracle_java_download_timeout: 60  
        oracle_java_rpm_filename: 'jdk-8u201-linux-x64.rpm'
        oracle_java_home: '/usr/java/default'
        oracle_java_os_supported: yes
        oracle_java_rpm_url: 'https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.rpm'
        oracle_java_rpm_validate_certs: yes
        oracle_java_set_as_default: no
        oracle_java_version_string: 1.8.0_201
```
