### ISSUE TITLE
Issue with oracle_java_rpm_url variable

### ISSUE THREAD

**Issue by alexandrnikitin** [ansiblebit/oracle-java#44]
I'm not sure what causes it yet 😕 
This playbook doesn't work:
```
---
- hosts: all
  roles:
     - role: ansiblebit.oracle-java
  vars:
    oracle_java_rpm_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_java_version }}u{{ oracle_java_version_update }}-b{{ oracle_java_version_build }}/d54c1d3a095b4ff2b6607d096fa80163/{{ oracle_java_rpm_filename }}"
    oracle_java_version_update: 131
    oracle_java_version_build: 11
```

If I put the `oracle_java_rpm_url` variable near the role it works:

```
---
- hosts: all
  roles:
     - { role: ansiblebit.oracle-java, oracle_java_rpm_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_java_version }}u{{ oracle_java_version_update }}-b{{ oracle_java_version_build }}/d54c1d3a095b4ff2b6607d096fa80163/{{ oracle_java_rpm_filename }}" }
  vars:
    oracle_java_version_update: 131
    oracle_java_version_build: 11
```
