### ISSUE TITLE
Java 6/7 Do not work on ubuntu

### ISSUE THREAD

**Issue by Dirrk** [ansiblebit/oracle-java#47]
Mocked playbook

```yaml
 - name: install java v7
   vars:
     oracle_java_set_as_default: false
     oracle_java_state: present
     oracle_java_version: 7
     oracle_java_home: /usr/lib/jvm/java-7-oracle
   roles:
    - ansiblebit.oracle-java
```

Result:
```
TASK [ansiblebit.oracle-java : debian | ensure Java is installed] *******************************************
task path: /Users/drada/workspace/code/cft-server-configs/ansible/galaxy_roles/ansiblebit.oracle-java/tasks/debian/main.yml:38
Using module file /usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/ansible/modules/packaging/os/apt.py
<192.168.244.2> ESTABLISH CONNECTION FOR USER: ubuntu on PORT 22 TO 192.168.244.2
<192.168.244.2> EXEC /bin/bash -c 'echo ~ && sleep 0'
<192.168.244.2> EXEC /bin/bash -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1497470518.57-136542900406420 `" && echo ansible-tmp-1497470518.57-136542900406420="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1497470518.57-136542900406420 `" ) && sleep 0'
<192.168.244.2> PUT /var/folders/0x/jl0rs2jx7bv1xwdfj1kk1ylm0000gn/T/tmpt2XNl4 TO /home/ubuntu/.ansible/tmp/ansible-tmp-1497470518.57-136542900406420/apt.py
<192.168.244.2> EXEC /bin/bash -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1497470518.57-136542900406420/ /home/ubuntu/.ansible/tmp/ansible-tmp-1497470518.57-136542900406420/apt.py && sleep 0'
<192.168.244.2> EXEC /bin/bash -c 'sudo -H -S -n -u root /bin/bash -c '"'"'echo BECOME-SUCCESS-hkovevwzffnuamqtyvnfilzkvuzrdvmq; /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1497470518.57-136542900406420/apt.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1497470518.57-136542900406420/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [weblocal01]: FAILED! => {
    "cache_update_time": 1497469415,
    "cache_updated": false,
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoremove": null,
            "cache_valid_time": 3600,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "install_recommends": null,
            "name": "oracle-java7-installer",
            "only_upgrade": false,
            "package": [
                "oracle-java7-installer"
            ],
            "purge": false,
            "state": "present",
            "update_cache": true,
            "upgrade": null
        }
    },
    "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'oracle-java7-installer'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n",
    "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n",
    "stderr_lines": [
        "E: Sub-process /usr/bin/dpkg returned an error code (1)"
    ],
    "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\noracle-java7-installer is already the newest version (7u80+7u60arm-0~webupd8~1).\n0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.\n1 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...\r\nDownloading Oracle Java 7...\r\n--2017-06-14 20:02:00--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz\r\nResolving download.oracle.com (download.oracle.com)... 23.62.7.139, 23.62.7.160\r\nConnecting to download.oracle.com (download.oracle.com)|23.62.7.139|:80... connected.\r\nHTTP request sent, awaiting response... 302 Moved Temporarily\r\nLocation: https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz [following]\r\n--2017-06-14 20:02:04--  https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz\r\nResolving edelivery.oracle.com (edelivery.oracle.com)... 23.49.182.138, 2001:418:1456:128d::2d3e, 2001:418:1456:12a7::2d3e\r\nConnecting to edelivery.oracle.com (edelivery.oracle.com)|23.49.182.138|:443... connected.\r\nHTTP request sent, awaiting response... 302 Moved Temporarily\r\nLocation: http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1497470649_4dfbcdfa6453dffd7d582e09dd6428ba [following]\r\n--2017-06-14 20:02:09--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1497470649_4dfbcdfa6453dffd7d582e09dd6428ba\r\nConnecting to download.oracle.com (download.oracle.com)|23.62.7.139|:80... connected.\r\nHTTP request sent, awaiting response... 404 Not Found\r\n2017-06-14 20:02:10 ERROR 404: Not Found.\r\n\r\ndownload failed\r\nOracle JDK 7 is NOT installed.\r\ndpkg: error processing package oracle-java7-installer (--configure):\r\n subprocess installed post-installation script returned error exit status 1\r\nErrors were encountered while processing:\r\n oracle-java7-installer\r\n",
    "stdout_lines": [
        "Reading package lists...",
        "Building dependency tree...",
        "Reading state information...",
        "oracle-java7-installer is already the newest version (7u80+7u60arm-0~webupd8~1).",
        "0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.",
        "1 not fully installed or removed.",
        "After this operation, 0 B of additional disk space will be used.",
        "Setting up oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...",
        "Downloading Oracle Java 7...",
        "--2017-06-14 20:02:00--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz",
        "Resolving download.oracle.com (download.oracle.com)... 23.62.7.139, 23.62.7.160",
        "Connecting to download.oracle.com (download.oracle.com)|23.62.7.139|:80... connected.",
        "HTTP request sent, awaiting response... 302 Moved Temporarily",
        "Location: https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz [following]",
        "--2017-06-14 20:02:04--  https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz",
        "Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.49.182.138, 2001:418:1456:128d::2d3e, 2001:418:1456:12a7::2d3e",
        "Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.49.182.138|:443... connected.",
        "HTTP request sent, awaiting response... 302 Moved Temporarily",
        "Location: http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1497470649_4dfbcdfa6453dffd7d582e09dd6428ba [following]",
        "--2017-06-14 20:02:09--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1497470649_4dfbcdfa6453dffd7d582e09dd6428ba",
        "Connecting to download.oracle.com (download.oracle.com)|23.62.7.139|:80... connected.",
        "HTTP request sent, awaiting response... 404 Not Found",
        "2017-06-14 20:02:10 ERROR 404: Not Found.",
        "",
        "download failed",
        "Oracle JDK 7 is NOT installed.",
        "dpkg: error processing package oracle-java7-installer (--configure):",
        " subprocess installed post-installation script returned error exit status 1",
        "Errors were encountered while processing:",
        " oracle-java7-installer"
    ]
}
```

This is related to: http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

My current work around was to create java-v7 role wrapper:

```yaml
 - name: create this directory /var/cache/oracle-jdk7-installer
   file:
     name: /var/cache/oracle-jdk7-installer
     state: directory

 - name: download the java file from local host
   get_url:
     checksum: "sha256:bad9a731639655118740bee119139c1ed019737ec802a630dd7ad7aab4309623"
     dest: /var/cache/oracle-jdk7-installer/jdk-7u80-linux-x64.tar.gz
     url: "https://xxxxxx/jdk-7u80-linux-x64.tar.gz"

 - name: copy the files to the installer directory
   copy:
     dest: /var/cache/oracle-jdk7-installer/{{ item }}
     src: "{{ item }}"
   with_items:
     - fontconfig.Ubuntu.properties
     - jar.binfmt
     - javaws-wrapper.sh
     - wgetrc

 - name: add external java v7 role
   include_role:
     name: ansiblebit.oracle-java
   vars:
     oracle_java_set_as_default: "{{ java_v7_default }}"
     oracle_java_state: "{{ java_v7_state }}"
     oracle_java_version: 7
     oracle_java_home: /usr/lib/jvm/java-7-oracle
```

I am posting this here since I didn't see anyone else mentioning this error and I am not sure how to fix this (without the workaround) or allow your role to do this in some way.

I tried on both Ubuntu 16 and Ubuntu 14
