### ISSUE TITLE
version: use releasesoftwaremoreoften.com

### ISSUE THREAD

**Issue by 030** [ansiblebit/oracle-java#79]
https://releasesoftwaremoreoften.com/latestversion?name=oraclejdk8

https://releasesoftwaremoreoften.com/latestversion?name=oraclejdk9

[Example](https://github.com/030/ansible-firefox/blob/master/tasks/main.yml#L2):
```
- name: get latest version information json url
  uri:
    url: http://releasesoftwaremoreoften.com/latestversion?name=firefox
    return_content: yes
  register: firefox_latest_version_info_url

- name: set firefox latest version information
  set_fact: firefox_latest_version_info="{{ firefox_latest_version_info_url.content }}"

- name: set latest version
  set_fact: firefox_version_latest="{{ firefox_latest_version_info.latestVersion }}"

- name: set latest checksum
  set_fact: firefox_checksum_latest="{{ firefox_latest_version_info.checksum }}"
```
