### ISSUE TITLE
Ubuntu Installation of Java 8 example points to Java 10 files

### ISSUE THREAD

**Issue by guzmonne** [ansiblebit/oracle-java#98]
The current example to install Java 8 on Ubuntu with this role says:

```yaml
- role: ansiblebit.oracle-java
        oracle_java_use_defaults: no
        oracle_java_apt_repository: "ppa:webupd8team/java"
        oracle_java_cache_valid_time: 3600
        oracle_java_deb_package: 'oracle-java10-installer'
        oracle_java_debconf_package_default: 'oracle-java10-set-default'
        oracle_java_home: "/usr/lib/jvm/java-10-oracle"
        oracle_java_set_as_default: no
        oracle_java_state: latest
```

But it should say:

```yaml
- role: ansiblebit.oracle-java
        oracle_java_use_defaults: no
        oracle_java_apt_repository: "ppa:webupd8team/java"
        oracle_java_cache_valid_time: 3600
        oracle_java_deb_package: 'oracle-java8-installer'
        oracle_java_debconf_package_default: 'oracle-java8-set-default'
        oracle_java_home: "/usr/lib/jvm/java-8-oracle"
        oracle_java_set_as_default: no
        oracle_java_state: latest
```
